-- Verificar si la base de datos 'IVC' existe, y si es así, eliminarla
IF EXISTS (
    SELECT
        name
    FROM
        sys.databases
    WHERE
        name = 'IVC'
) BEGIN
DROP DATABASE IVC;

END 
GO
-- Crear la base de datos 'IVC'
CREATE DATABASE IVC;

GO
-- Usar la base de datos recién creada
USE IVC;

GO
CREATE TABLE
    LINEA_DE_GESTION (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOMBRE VARCHAR(255),
        GRUPO VARCHAR(255),
        REPARTICION VARCHAR(255),
        TIPO VARCHAR(255)
    );

GO
CREATE TABLE
    LINEA_DE_GESTION_FF (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        ID_LINEA_GESTION INT,
        NOMBRE_FF VARCHAR(255),
        FUENTE VARCHAR(255) FOREIGN KEY (ID_LINEA_GESTION) REFERENCES LINEA_DE_GESTION (ID),
    );

GO
-- Tabla de FF CTA ESC
CREATE TABLE
    FF_CTA_ESC (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        CTA_ESCRITURAL VARCHAR(50) UNIQUE,
        FUENTE_FIN VARCHAR(255),
        FUENTE_ORIGEN VARCHAR(255)
    );

GO
-- Tabla de equivalencias
CREATE TABLE
    EQUIVALENCIAS (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        CONCATENADO VARCHAR(55) UNIQUE,
        CLASIFICACION VARCHAR(255),
        LINEA_DE_GESTION INT,
        TIPO_GASTO VARCHAR(50),
        REPARTICION VARCHAR(255),
        FOREIGN KEY (LINEA_DE_GESTION) REFERENCES LINEA_DE_GESTION (ID)
    );

GO
-- Tabla de parametrizado
CREATE TABLE
    PARAMETRIZADO (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        SECTOR VARCHAR(255),
        SUBSECTOR VARCHAR(255),
        CARACTER VARCHAR(255),
        JURISDICCION VARCHAR(255),
        SUBJURISDICCION VARCHAR(255),
        ENTIDAD VARCHAR(255),
        OGESE VARCHAR(50),
        UNIDAD_EJECUTORA VARCHAR(255),
        PROGRAMA VARCHAR(255),
        SUBPROGRAMA VARCHAR(255),
        PROYECTO VARCHAR(255),
        ACTIVIDAD VARCHAR(255),
        OBRA INT,
        CUENTA_ESCRITURAL VARCHAR(50),
        MONEDA VARCHAR(50),
        FINALIDAD VARCHAR(255),
        FUNCION VARCHAR(50),
        INCISO VARCHAR(50),
        PARTIDA_PRINCIPAL VARCHAR(50),
        PARTIDA_PARCIAL VARCHAR(50),
        PARTIDA_SUBPARCIAL VARCHAR(50),
        CLAS_ECONOMICO VARCHAR(50),
        FUENTE_FINANCIERA VARCHAR(50),
        UBICACION_GEO VARCHAR(255),
        ACT_INT VARCHAR(50),
        DESCRIPCION VARCHAR(255),
        SANCION DECIMAL(15, 2),
        VIGENTE DECIMAL(15, 2),
        PREVENTIVO DECIMAL(15, 2),
        RESTRINGIDO DECIMAL(15, 2),
        DEFINITIVO DECIMAL(15, 2),
        RESERVA_COMPROMISO DECIMAL(15, 2),
        DEVENGADO DECIMAL(15, 2),
        PAGADO DECIMAL(15, 2),
        DISPONIBLE DECIMAL(15, 2),
        LIQUIDADO DECIMAL(15, 2),
        TOTAL_AFECTACION_PRE DECIMAL(15, 2),
        TOTAL_AFECTACION_DEF DECIMAL(15, 2),
        TOTAL_AFECTACION_DEV DECIMAL(15, 2),
        CONCATENADO_SF AS (
            CAST(
                COALESCE(PROGRAMA, '') + '-' + COALESCE(PROYECTO, '') + '-' + COALESCE(ACTIVIDAD, '') + '-' + CAST(COALESCE(OBRA, 0) AS VARCHAR) + '-' + COALESCE(INCISO, '') + '-' + COALESCE(PARTIDA_PRINCIPAL, '') + '-' + COALESCE(PARTIDA_PARCIAL, '') AS VARCHAR(55)
            )
        ) PERSISTED,
        PARTIDA_CALCULADA AS (
            COALESCE(PROGRAMA, '') + '-' + COALESCE(SUBPROGRAMA, '') + '-' + COALESCE(PROYECTO, '') + '-' + COALESCE(ACTIVIDAD, '') + '-' + COALESCE(OBRA, '')
        ) PERSISTED,
        INCISO_CALCULADO AS (
            COALESCE(INCISO, '') + '-' + COALESCE(PARTIDA_PRINCIPAL, '') + '-' + COALESCE(PARTIDA_PARCIAL, '')
        ) PERSISTED,
        FOREIGN KEY (CONCATENADO_SF) REFERENCES EQUIVALENCIAS (CONCATENADO),
        FOREIGN KEY (CUENTA_ESCRITURAL) REFERENCES FF_CTA_ESC (CTA_ESCRITURAL)
    );

GO
-- Tabla de devengados
CREATE TABLE
    DEVENGADOS (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        EJERCICIO INT,
        NUMERO_DEVENGADO INT NOT NULL,
        ESTADO_FIRMA VARCHAR(50),
        EXPEDIENTE VARCHAR(50),
        ENTE VARCHAR(255),
        CUIT VARCHAR(20),
        DESCRIPCION VARCHAR(255),
        OBRA INT,
        IMPORTE_DEVENGADO DECIMAL(15, 2),
        JURISDICCION VARCHAR(50),
        SUB_JURISDICCION VARCHAR(50),
        ENTIDAD VARCHAR(255),
        PROGRAMA VARCHAR(255),
        SUB_PROGRAMA VARCHAR(255),
        PROYECTO VARCHAR(255),
        ACTIVIDAD VARCHAR(255),
        OBRA2 INT,
        INCISO VARCHAR(50),
        PRINCIPAL VARCHAR(50),
        PARCIAL VARCHAR(50),
        SUB_PARCIAL VARCHAR(50),
        FUENTE_FINANCIERA VARCHAR(255),
        UBICACION_GEO VARCHAR(255),
        CUENTA_ESCRITURAL VARCHAR(50),
        CUENTA_PAGADORA VARCHAR(50),
        IMPORTE_PP DECIMAL(15, 2),
        IMPORTE_PAGADO DECIMAL(15, 2),
        SALDO_A_PAGAR_PP DECIMAL(15, 2),
        TOTAL_DEVENGADO DECIMAL(15, 2),
        TOTAL_PAGADO DECIMAL(15, 2),
        DEUDA_DEV DECIMAL(15, 2),
        FECHA_IMPUTACION DATE,
        EE_FINANCIERA VARCHAR(50),
        EE_AUTORIZANTE VARCHAR(50),
        MONTO_DEVENGADO DECIMAL(15, 2),
        CONCATENADO_SF AS (
            CAST(
                COALESCE(PROGRAMA, '') + '-' + COALESCE(PROYECTO, '') + '-' + COALESCE(ACTIVIDAD, '') + '-' + CAST(COALESCE(OBRA, 0) AS VARCHAR) + '-' + COALESCE(INCISO, '') + '-' + COALESCE(PRINCIPAL, '') + '-' + COALESCE(PARCIAL, '') AS VARCHAR(55)
            )
        ) PERSISTED,
        TIPO AS (
            CASE
                WHEN PROYECTO = 0 THEN 'GC'
                ELSE 'PPI'
            END
        ) PERSISTED,
        FOREIGN KEY (CONCATENADO_SF) REFERENCES EQUIVALENCIAS (CONCATENADO),
        FOREIGN KEY (CUENTA_ESCRITURAL) REFERENCES FF_CTA_ESC (CTA_ESCRITURAL)
    );

GO
-- Tabla de áreas
CREATE TABLE
    AREAS (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOMBRE VARCHAR(255)
    );

GO
-- Tabla de empresas
CREATE TABLE
    EMPRESAS (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOMBRE VARCHAR(255)
    );

GO
-- Tabla de CONTRATA
CREATE TABLE
    CONTRATA (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOMBRE VARCHAR(255)
    );

GO
CREATE TABLE
    BARRIOS (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOMBRE VARCHAR(255)
    );
	GO
CREATE TABLE USUARIOS (
    ID INT IDENTITY(1, 1) PRIMARY KEY,    -- Identificador único para cada usuario
    NOMBRE VARCHAR(255),                   -- Nombre del usuario
    CORREO VARCHAR(255),                   -- Correo electrónico
    CONTRASENIA VARCHAR(255),               -- Contraseña del usuario
    TIPO bit default 0,         -- Tipo de usuario '0' user '1' admin)
	ESTADO BIT default 0,
	AREA INT
	FOREIGN KEY (AREA) REFERENCES AREAS (ID)
);
GO


go
use IVC
--SELECT * FROM USUARIOS WHERE (CORREO = '123@gmail.com' OR NOMBRE = 'nah') AND CONTRASENIA = '123'
--select * from USUARIOS inner join AREAS as a on AREA = a.ID
-- Tabla de obras


CREATE TABLE
    OBRAS (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        AREA INT NOT NULL,
        EMPRESA INT NOT NULL,
        NUMERO INT,
        CONTRATA INT,
        AÑO INT,
        ETAPA INT,
        OBRA INT,
        BARRIO INT,
        DESCRIPCION VARCHAR(255), --nombre
        FOREIGN KEY (AREA) REFERENCES AREAS (ID),
        FOREIGN KEY (EMPRESA) REFERENCES EMPRESAS (ID),
        FOREIGN KEY (CONTRATA) REFERENCES CONTRATA (ID),
        FOREIGN KEY (BARRIO) REFERENCES BARRIOS (ID)
    );

GO
CREATE TABLE
    ESTADOS_REDET (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOMBRE VARCHAR(255)
    );

GO
CREATE TABLE
    ESTADOS_AUTORIZANTES (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOMBRE VARCHAR(255)
    );

GO
-- Tabla de autorizantes
CREATE TABLE
    AUTORIZANTES (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        OBRA INT,
        CODIGO_AUTORIZANTE VARCHAR(50) UNIQUE,
        DETALLE VARCHAR(255),
        CONCEPTO VARCHAR(255),
        ESTADO INT,
        EXPEDIENTE VARCHAR(50),
        MONTO_AUTORIZADO DECIMAL(15, 2),
		MES DATE,
        AUTORIZACION_GG BIT NOT NULL DEFAULT 0,
        FOREIGN KEY (OBRA) REFERENCES OBRAS (ID),
        FOREIGN KEY (ESTADO) REFERENCES ESTADOS_AUTORIZANTES (ID)
    );

GO
-- Tabla de redeterminaciones
CREATE TABLE
    REDETERMINACIONES (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        ID_BASE INT,
        CODIGO_AUTORIZANTE VARCHAR(50),
        EXPEDIENTE VARCHAR(50),
        SALTO DATE,
        NRO INT,
        TIPO VARCHAR(50),
        ETAPA INT,
        OBSERVACIONES VARCHAR(255),
        CODIGO_REDET AS (
            COALESCE(CODIGO_AUTORIZANTE, '') + '-R' + CAST(COALESCE(NRO, '') AS VARCHAR)
        ) PERSISTED,
        FOREIGN KEY (ID_BASE) REFERENCES OBRAS (ID),
        FOREIGN KEY (ETAPA) REFERENCES ESTADOS_REDET (ID),
        FOREIGN KEY (CODIGO_AUTORIZANTE) REFERENCES AUTORIZANTES (CODIGO_AUTORIZANTE)
    );

GO
-- Tabla de disposiciones
CREATE TABLE
    DISPOSICIONES (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        EXPEDIENTE VARCHAR(50) UNIQUE NOT NULL,
        FECHA DATE,
        DISPO VARCHAR(50),
        INFO_NOTIFICACION VARCHAR(255)
    );

GO
-- Tabla de actas acuerdo
CREATE TABLE
    ACTAS_ACUERDO (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        EXPEDIENTE VARCHAR(50) UNIQUE NOT NULL,
        FECHA DATE,
        ACTA_ACUERDO VARCHAR(255),
        RTA_DICTAMEN VARCHAR(255)
    );

GO
CREATE TABLE
    TIPO_PAGO (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        NOMBRE VARCHAR(255)
    );

GO
-- Tabla de certificados
CREATE TABLE
    CERTIFICADOS (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        CODIGO_AUTORIZANTE VARCHAR(50) NOT NULL,
        EXPEDIENTE_PAGO VARCHAR(50),
        TIPO_PAGO INT,
        MONTO_TOTAL DECIMAL(15, 2),
        MES_APROBACION DATE,
        FOREIGN KEY (CODIGO_AUTORIZANTE) REFERENCES AUTORIZANTES (CODIGO_AUTORIZANTE),
        FOREIGN KEY (TIPO_PAGO) REFERENCES TIPO_PAGO (ID)
    );

GO
-- Tabla de BD proyectos
CREATE TABLE
    BD_PROYECTOS (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        ID_BASE INT UNIQUE NOT NULL,
        SUBPROYECTO VARCHAR(255) UNIQUE NOT NULL,
        PROYECTO VARCHAR(255),
        LINEA_DE_GESTION INT,
        AUTORIZADO_INICIAL DECIMAL(15, 2),
        AUTORIZADO_NUEVO DECIMAL(15, 2),
        FOREIGN KEY (ID_BASE) REFERENCES OBRAS (ID),
        FOREIGN KEY (LINEA_DE_GESTION) REFERENCES LINEA_DE_GESTION (ID)
    );

GO
-- Tabla de legítimos abonos
CREATE TABLE
    LEGITIMOS_ABONOS (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        OBRA INT,
        CODIGO_AUTORIZANTE VARCHAR(50) NOT NULL,
        EXPEDIENTE VARCHAR(50),
        INICIO_EJECUCION DATE,
        FIN_EJECUCION DATE,
        CERTIFICADO DECIMAL(15, 2),
        MES_APROBACION DATE,
        FOREIGN KEY (OBRA) REFERENCES OBRAS (ID)
    );

GO
-- Crear la tabla FORMULACION
CREATE TABLE
    FORMULACION (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        AREA INT,
        CONTRATA VARCHAR(255),
        NUMERO INT,
        AÑO INT,
        ETAPA VARCHAR(50),
        OBRA INT,
        NOMBRE VARCHAR(255),
        TIPO VARCHAR(50),
        BARRIO VARCHAR(255),
        ID_EMPRESA INT,
        OBRA_SERVICIO VARCHAR(255),
        MONTO_AUTORIZADO DECIMAL(15, 2),
        FOREIGN KEY (AREA) REFERENCES AREAS (ID),
        FOREIGN KEY (OBRA) REFERENCES OBRAS (ID),
        FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID)
    );

GO
-- Crear la tabla PASES_SADE
CREATE TABLE
    PASES_SADE (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        EXPEDIENTE VARCHAR(50) NOT NULL,
        FECHA_ULTIMO_PASE DATE,
        BUZON_DESTINO VARCHAR(255),
        FECHA_PRIMER_PASE DATE,
        EXPEDIENTE_CALCULADO VARCHAR(55) -- ARMAR TRIGGER   
    );

GO
CREATE TABLE
    MOVIMIENTOS_GESTION (
        ID INT IDENTITY (1, 1) PRIMARY KEY,
        ID_BASE INT NOT NULL,
        MOVIMIENTO DECIMAL(15, 2),
        FECHA DATE,
        FOREIGN KEY (ID_BASE) REFERENCES OBRAS (ID)
    );

-- TRIGGER
GO 
CREATE TRIGGER trg_set_autorizado_nuevo ON BD_PROYECTOS AFTER INSERT AS BEGIN
UPDATE BD_PROYECTOS
SET
    AUTORIZADO_NUEVO = P.AUTORIZADO_INICIAL
FROM
    BD_PROYECTOS P
    INNER JOIN inserted I ON P.ID = I.ID
WHERE
    P.ID = I.ID;

END;

GO 
CREATE TRIGGER trg_update_autorizado_nuevo ON MOVIMIENTOS_GESTION AFTER INSERT AS BEGIN
UPDATE BD_PROYECTOS
SET
    AUTORIZADO_NUEVO = AUTORIZADO_INICIAL + (
        SELECT
            SUM(MOVIMIENTO)
        FROM
            MOVIMIENTOS_GESTION
        WHERE
            MOVIMIENTOS_GESTION.ID_BASE = BD_PROYECTOS.ID_BASE
    )
WHERE
    EXISTS (
        SELECT
            1
        FROM
            MOVIMIENTOS_GESTION
        WHERE
            MOVIMIENTOS_GESTION.ID_BASE = BD_PROYECTOS.ID_BASE
    );

END;

GO
CREATE TRIGGER TRG_Autorizantes_Insert
ON AUTORIZANTES
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    -- Actualizar CODIGO_AUTORIZANTE asegurando unicidad
    UPDATE AUTORIZANTES
    SET CODIGO_AUTORIZANTE = CONCAT(i.OBRA, '-', 
                                    ISNULL((
                                        SELECT COUNT(*) 
                                        FROM AUTORIZANTES 
                                        WHERE OBRA = i.OBRA AND ID <= i.ID
                                    ), 0))
    FROM AUTORIZANTES a
    INNER JOIN INSERTED i ON a.ID = i.ID;
END;
GO
-- INSERT
INSERT INTO
    EMPRESAS (NOMBRE)
VALUES
    ('CONSEJO PROFESIONAL DE AGRIMENSURA'),
    ('IVC SUBGERENCIA TESORERIA'),
    ('PRINT TEAM SRL'),
    ('COOPERATIVA DE TRABAJO 8 DE SEPTIEMBRE LIMITADA'),
    ('BANCO DE LA CIUDAD DE BUENOS AIRES'),
    ('COOPERATIVA DE TRABAJO 10 DE DICIEMBRE LIMITADA'),
    ('MARÍA DOLORES GARRIDO OROMÍ'),
    (
        'IVC COORDINACION GENERAL GESTION SOCIAL DE LA VIVIENDA'
    ),
    ('IVC_GERENCIA ADMINISTRACION Y FINANZAS'),
    ('IVC_GERENCIA GENERAL'),
    ('AGUA Y SANEAMIENTOS ARGENTINOS SOCIEDAD ANONIMA'),
    (
        'IVC_DIRECCION GENERAL DESARROLLO SOCIOTERRITORIAL'
    ),
    ('IVC_DIRECTOR III'),
    (
        'IVC GERENCIA COORDINACION GENERAL OBRAS Y SERVICIOS'
    ),
    ('IVC_DIRECCION GENERAL DESARROLLO DE PROYECTOS'),
    ('IVC_PRESIDENCIA'),
    (
        'IVC_GERENCIA DE COORDINACION GENERAL LEGAL Y TECNICA'
    ),
    (
        'IVC DIRECCIÓN GENERAL DE GESTION DE INTERVENCION SOCIAL'
    ),
    ('AUTOPISTAS DE BUENOS AIRES (AUBASA) S.A'),
    ('COOPERATIVA DE TRABAJO BARRIO NUEVO LTDA'),
    ('CORREDORES VIALES SOCIEDAD ANONIMA'),
    (
        'COORDINACION ECOLOGICA AREA METROPOLITANA SOCIEDAD DEL ESTADO'
    ),
    ('AUTOPISTAS URBANAS S.A.'),
    ('UNIVERSIDAD NACIONAL DE GENERAL SAN MARTIN'),
    ('GRUPO CONCESIONARIO DEL OESTE S.A.'),
    ('JUAN CARLOS SAVINO'),
    ('LINO JOSE CAPELO'),
    ('AUTOPISTAS DEL SOL S.A.'),
    ('CONSTRUCTORA SERVICIOS DE CATEGORIA SA'),
    ('VIDOGAR CONSTRUCCIONES S.A.'),
    ('VILLAREX S.A.'),
    ('COOPERATIVA DE TRABAJO 2 DE ABRIL LIMITADA'),
    ('EMPLEADOS IVC'),
    (
        'LA SEGUNDA COOPERATIVA LIMITADA DE SEGUROS GENERALES'
    ),
    ('BLUE STEEL S. A.'),
    ('DEMOLICIONES MITRE SRL'),
    ('COOPERATIVA DE TRABAJO EL PROGRESO LIMITADA'),
    ('COOPERATIVA DE TRABAJO FUERZA Y COMPROMISO LTDA'),
    ('COOPERATIVA DE TRABAJO LOGRAR Y CRECER LIMITADA'),
    ('COOPERATIVA DE VIVIENDA SAN JUDAS LTDA'),
    (
        'COOPERATIVA DE VIVIENDA, CREDITO Y CONSUMO TRES CUARENTA Y UNO'
    ),
    ('GRUPO FARALLON DESARROLLOS INMOBILIARIOS S.A'),
    ('MIAVASA S.A.'),
    ('COOPERATIVA DE TRABAJO NUEVO AMANECER LIMITADA'),
    ('ILUBAIRES S.A.'),
    ('COOPERATIVA DE TRABAJO CRECER LIMITADA'),
    ('AUTOMAT ARGENTINA S. A.'),
    ('ASOCIACION CIVIL NUESTRO HOGAR'),
    ('CRIBA SA'),
    ('COOPERATIVA DE VIVIENDA BRASIL 1517 LTDA'),
    (
        'ORGANIZACION DE ESTADOS IBEROAMERICANOS PARA LA EDUCACION LA CIENCIA Y LA CULTURA'
    ),
    ('COOPERATIVA DE TRABAJO 9 DE JUNIO LIMITADA'),
    ('ROMERO ROMINA'),
    ('FEMYP S.R.L'),
    ('COOPERATIVA DE TRABAJO JUVENTUD UNIDA LIMITADA'),
    (
        'COOPERATIVA DE TRABAJO DE MANTENIMIENTO Y CONSTRUCCION SAN ROQUE LIMITADA'
    ),
    ('KEVIN DINTER'),
    ('BCO DE LA CIUDAD DE BS AS TASACIONES'),
    ('GIRALDI LOENGRIN ERVAR'),
    ('PEREYRA NORMA ANTONIA'),
    ('CONSORCIO DE PROPIETARIOS A.ZORRILLA 4404/12/14'),
    ('VIAL ALFANO SA'),
    ('VIVIAN HNOS SA'),
    ('DISAB SUDAMERICANA S.A.'),
    ('EDENRED ARGENTINA S.A.'),
    ('CONSEJO NACIONAL DE LA VIVIENDA'),
    ('CARMEN DOLORES CAPELO ALVELA'),
    ('COOPERATIVA DE TRABAJO LA SOLIDARIDAD LTDA'),
    (
        'COOPERATIVA DE VIVIENDA, CREDITO Y CONSUMO MARIA DEL ROSARIO LTDA.'
    ),
    ('MEGACER S.R.L.'),
    (
        'ADMINISTRACION GUBERNAMENTAL DE INGRESOS PUBLICOS (AGIP)'
    ),
    ('OPERYS S.R.L.'),
    ('IVC_INGRESOS BRUTOS'),
    (
        'SERVICIOS DE ASISTENCIA INDUSTRIAL Y CONSTRUCCIONES SRL'
    ),
    (
        'COLEGIO DE ESCRIBANOS DE LA PCIA DE BS AS CONVENIO CON DIRECCION DE LA PROPIEDAD'
    ),
    (
        'COOPERATIVA DE VIVIENDA Y CONSUMO EL MOLINO LTDA'
    ),
    (
        'COOPERATIVA DE VIVIENDA LA UNIÓN DE SAAVEDRA LTDA'
    ),
    ('LAURENCE JAVIER DRUSCOVICH'),
    ('COOPERATIVA DE TRABAJO SAN CAYETANO LTDA.'),
    (
        'NOSIS LABORATORIO DE INVESTIGACION Y DESARROLLO S.A.'
    ),
    ('COOPERATIVA DE VIVIENDA URITORCO LTDA.'),
    ('COOPERATIVA DE VIVIENDA GARIBALDI LTDA.'),
    (
        'COOPERATIVA DE VIVIENDA Y CONSUMO ASAMBLEA PRIMERO DE MAYO LTDA'
    ),
    ('COOPERATIVA DE TRABAJO 23 DE AGOSTO LTDA'),
    ('SERVICIOS IBARRA S.R.L.'),
    ('COOPERATIVA DE VIVIENDA SURCO LIMITADA'),
    ('TNGROUP S.A.'),
    ('COOPERATIVA DE TRABAJO ASUMA LIMITADA'),
    (
        'FUNDACIÓN METÁFORA PARA EL DESARROLLO SUSTENTABLE Y LA COOPERACIÓN INTERNACIONAL'
    ),
    (
        'INCLUIR INSTITUTO PARA LA INCLUSION SOC Y EL DESRR HUMANO ASOC CIV'
    ),
    (
        'ASOCIACION CIVIL OBSERVATORIO DEL DERECHO A LA CUIDAD'
    ),
    (
        'ASOCIACION CIVIL GRUPOS DE ESTUDIANTES SOLIDARIOS'
    ),
    (
        'ASOCIACION CIVIL GRUPO COMUNITARIO Y EDUCATIVO RAICES'
    ),
    (
        'COO. DE VIVIENDA LOS VECINOS LUCHADORES LIMITADA'
    ),
    (
        'COOPERATIVA DE TRABAJO GESTAR BARRIO RODRIGO BUENO LIMITADA'
    ),
    ('COOPERATIVA DE TRABAJO 4 DE SEPTIEMBRE LIMITADA'),
    ('COOPERATIVA DE TRABAJO SIN FRONTERAS LIMITADA'),
    ('COOPERATIVA DE TRABAJO LAS PALMAS LTDA'),
    ('COOPERATIVA DE TRABAJO VAMOS POR MAS LIMITADA'),
    ('COOPERATIVA DE TRABAJO SURACTIVO LIMITADA'),
    ('COOPERATIVA DE TRABAJO LOS MONOBLOCKS LIMITADA'),
    ('COOPERATIVA DE TRABAJO LUJAN PUEDE LIMITADA'),
    ('COOPERATIVA DE TRABAJO SANTA CATALINA LIMITADA'),
    ('COOPERATIVA DE TRABAJO EL SUR EN MARCHA  LTDA.'),
    ('COOPERATIVA DE TRABAJO PUEBLO UNIDO LIMITADA'),
    ('COOPERATIVA DE TRABAJO MANOS A LA OBRA LTDA'),
    (
        'COOPERATIVA DE TRABAJO CONSTRUYENDO UN FUTURO LIMITADA'
    ),
    ('COOPERATIVA DE TRABAJO LA 25 LIMITADA'),
    ('COOPERATIVA DE TRABAJO UNIDOS A MUJICA LIMITADA'),
    ('IVC_RETENCION GANANCIAS'),
    ('IVC_RETENCION PREVISIONAL'),
    ('COOPERATIVA DE TRABAJO DEDOS EN V 4 LIMITADA'),
    ('TEJIENDO CULTURA ASOCIACION CIVIL'),
    ('COOPERATIVA DE TRABAJO LA RUDA LIMITADA'),
    ('COLQUE GUSTAVO'),
    ('COOPERATIVA DE VIVIENDA EL PORVENIR LIMITADA'),
    ('COOPERATIVA DE TRABAJO EL GUAPO LIMITADA'),
    (
        'COOPERATIVA DE VIVIENDA CREDITO Y CONSUMO DEL SUR LTDA'
    ),
    ('CARGAS RAMOS S.A.'),
    ('AUTOTROL S.A.'),
    ('SILVIA BEATRIZ LUIS'),
    (
        'UNIVERSIDAD TECNOLÓGICA NACIONAL - FACULTAD REGIONAL DE BUENOS AIRES'
    ),
    ('CONFERENCIAS SRL'),
    ('COOPERATIVA DE TRABAJO HACER LIMITADA'),
    ('SOLUCIONES EN LOGÍSTICA LRM S.R.L'),
    ('JON MARCELO CASTILLO ALCOCER'),
    ('CONSTRUCTORA RENOVA S.R.L.'),
    ('VIAJES APOLO S.R.L'),
    ('COOPERATIVA DE TRABAJO PERICO LIMITADA'),
    ('COOPERATIVA DE TRABAJO 26 DE JULIO LIMITADA'),
    ('LIMA JUAN MANUEL'),
    ('CODERHOUSE SRL'),
    ('EDUCORP SRL'),
    (
        'ESTUDIO DIEZ SOCIEDAD LEY 19550 CAP I SECCION IV'
    ),
    ('COOPERATIVA DE TRABAJO 26 DE NOVIEMBRE LIMITADA'),
    ('ING EUGENIO MENDIGUREN SA'),
    ('LUZ DEL SUR - LDS MANTENIMIENTO ELECTRICO S.A.'),
    ('CLAUDIO GUSTAVO SEGOBIA CAPELO'),
    ('EDESUR'),
    ('TELEFONICA MOVILES ARGENTINA S.A.'),
    ('METROGAS SA'),
    ('TELEFONICA DE ARGENTINA  S.A'),
    ('CORREO OFICIAL DE LA REPÚBLICA ARGENTINA S.A.'),
    ('EDENOR'),
    ('KYOTO URBAN DATA S.A.S.'),
    ('MATAFUEGOS DONNY SRL'),
    ('SERVICIOS DEL RIO DE LA PLATA S.R.L.'),
    ('SAMUEL ALFREDO VORCHHEIMER'),
    ('COOPERATIVA DE TRABAJO 16 DE NOVIEMBRE LIMITADA'),
    ('COOPERATIVA DE TRABAJO 24 DE ABRIL LIMITADA'),
    ('COOPERATIVA DE TRABAJO SOCA LIMITADA'),
    ('BENCEN CONSTRUCCIONES SRL'),
    ('LIBUS  S.A.'),
    ('FISCHETTI Y CIA. S.R.L.'),
    ('ARTFUL S.A.'),
    ('CIAGESER S.A.'),
    ('NORBERTO DANIEL CABEZAS'),
    ('COOPERATIVA DE TRABAJO 15 DE OCTUBRE LIMITADA'),
    ('ASHIRA S.A.'),
    ('COOPERATIVA DE TRABAJO UNIVERSAL LIMITADA'),
    ('SERVICIOS PARA LA HIGIENE S.A'),
    ('AP SUPPLIER GROUP SA'),
    ('STARTUP SRL'),
    ('B.A.SANI S.A.'),
    ('LICICOM S.R.L.'),
    ('MOTYVAR SRL'),
    ('DIGITAL STRATEGY SAS'),
    ('TRESCOM S.R.L.'),
    ('EUQUI S.A.'),
    ('SERVICIOS INTEGRALES LOGISTICOS S.A.'),
    ('INDUSTRIAS MAS SRL'),
    ('PATAGONYKA GROUP S.A.'),
    ('MELENZANE SA'),
    ('RED DE BARRIOS ASOCIACIÓN CIVIL'),
    ('TEXTISUR S.R.L.'),
    ('FRANCISCO OSVALDO DIAZ S.A.'),
    ('JOTA TECHNOLOGY SRL'),
    ('CORADIR S.A.'),
    ('WALTER ALSINA'),
    ('ERRE-DE SRL'),
    ('EXTERNAL MARKET S.R.L.'),
    ('GUSTAVO MANUEL OZEMO'),
    ('ASHOKA CONSTRUCCIONES SA'),
    ('CAMUT S. R. L.'),
    ('AVANTECNO S.A'),
    ('JUAN ERNESTO IBARRA'),
    ('SILVIA GABRIELA BARDELLI');
	GO
INSERT INTO
    BARRIOS (nombre)
VALUES
    ('RODRIGO BUENO'),
    ('FRAGA'),
    ('ZAVALETA'),
    ('VILLA 21-24'),
    ('VILLA 20'),
    ('SOLDATI'),
    ('PIEDRABUENA'),
    ('PADRE MUGICA'),
    ('LA BOCA'),
    ('COLONIA SOLA'),
    ('CARRILLO'),
    ('VARIOS'),
    ('ASENTAMIENTOS'),
    ('VILLA 15'),
    ('FÁTIMA'),
    ('PADRE RODOLFO RICCIARDELLI'),
    ('SAN FRANCISCO'),
    ('RIVADAVIA'),
    ('ESPORA NORTE Y SUR'),
    ('ILLIA'),
    ('JUSTO SUÁREZ'),
    ('LAMADRID'),
    ('BAJO FLORES'),
    ('BARRIO 15 - EDIFICIOS A, B, C, D Y F'),
    ('BARRIO 15 - MZ 27- A-D'),
    ('BARRIO 15 - NHT EVA PERON 6600'),
    ('BONORINO I-IV'),
    ('CALAZA'),
    ('CASTRO Y SAMORE'),
    ('CILDAÑEZ'),
    ('COPELLO'),
    ('DORREGO - J SUAREZ'),
    ('ESPORA SUR Y NORTE'),
    ('LACARRA'),
    ('LUGANO I Y II'),
    ('LUGANO XXVII'),
    ('PIRELLI'),
    ('RIVADAVIA II'),
    ('MUGICA'),
    ('BONORINO I - VI'),
    ('VILLA 26'),
    ('PARQUE DE LAS VICTORIAS'),
    ('PLAYON DE CHACARITA'),
    ('BONORINO I-VI'),
    ('DORREGO / J. SUAREZ'),
    ('BARRIO 15 EDIFICIOS DE LA A A LA F'),
    ('RIVADAVIA 2'),
    ('CASTRO SAMORE'),
    ('MARTIN RODRIGUEZ'),
    ('CASTEX'),
    ('SAVIO'),
    ('BARRIO'),
    ('BARRIO 20'),
    ('VALPARAISO VERACRUZ'),
    ('PADRE GROTE'),
    ('SAN ANTONIO'),
    ('RAMÓN CARRILLO'),
    ('BARRIO 15'),
    ('SUAREZ'),
    ('OSVALDO CRUZ Y LUNA'),
    ('ORMA'),
    ('RIVERA IGUAZÚ'),
    ('CORONEL SALVADORES'),
    ('ALVARADO'),
    ('1.11.14'),
    ('21.24'),
    ('SALVADORES 829'),
    ('SALVADORES 825'),
    ('ORMA');
	GO
INSERT INTO
    AREAS (NOMBRE)
VALUES
    ('DGDO'),
    ('DGDH'),
    ('DGGIS'),
    ('MODERNIZACION'),
    ('DGTAL'),
    ('DG DESARROLLO DE PROYECTOS'),
    ('SOCIAL'),
    ('GOM');
	GO
INSERT INTO
    CONTRATA (NOMBRE)
VALUES
    ('LP'),
    ('LA'),
    ('CV'),
    ('CDU'),
    ('CD'),
    ('CM'),
    ('CONT'),
    ('OC'),
    ('433');
	GO
INSERT INTO
    TIPO_PAGO (NOMBRE)
VALUES
    ('ANTICIPO FINANCIERO'),
    ('CERTIFICADO'),
    ('RELIQUIDACION');
	GO
INSERT INTO
    ESTADOS_AUTORIZANTES (NOMBRE)
VALUES
    ('APROBADO'),
    ('EN TRAMITE'),
    ('DESESTIMADO'),
    ('NO INICIADO');
	GO
INSERT INTO
    ESTADOS_REDET (NOMBRE)
VALUES
    ('RD-01/11-Subsanacion Empresa'),
    ('RD-02/11-Análisis Tecnica'),
    ('RD-03/11-Análisis DGAyF'),
    ('RD-04/11-Dgtal-Dictamen'),
    ('RD-04a/11-Tecnica Rta Dictamen'),
    ('RD-05/11-Firma AA Empresa'),
    ('RD-06/11-Firma AA cd'),
    ('RD-07/11-Aprobacion Anterior'),
    ('RD-08/11-Reser. Presup'),
    ('RD-09/11-Dgtal-Dispo'),
    ('RD-10/11-Notificar a la empresa'),
    ('RD-11/11-Notificada'),
    ('RP-01/09-Subsanacion Empresa'),
    ('RP-02/09-Análisis Tecnica'),
    ('RP-03/09-Análisis DGAyF'),
    ('RP-04/09-Dgtal-Dictamen'),
    ('RP-04a/09-Tecnica Rta Dictamen'),
    ('RP-05/09-Aprobacion Anterior'),
    ('RP-06/09-Reser. Presup'),
    ('RP-07/09-Dgtal-Dispo'),
    ('RP-08/09-Notificar a la empresa'),
    ('RP-09/09-Notificada'),
    ('RO-01/11-Creacion Expediente'),
    ('RO-02/11-Análisis Tecnica'),
    ('RO-03/11-Análisis DGAyF'),
    ('RO-04/11-Dgtal-Dictamen'),
    ('RO-05/11-Firma AA Empresa'),
    ('RO-06/11-Firma AA cd'),
    ('RO-07/11-Aprobacion Anterior'),
    ('RO-08/11-Reser. Presup'),
    ('RO-09/11-Dgtal-Dispo'),
    ('RO-10/11-Notificar a la empresa'),
    ('RO-11/11-Notificada'),
    ('Rectificacion'),
    ('Rechazada'),
    ('Fuera de Plazo'),
    ('Pendiente'),
    ('No presentada'),
    ('ACDIR');
	GO

INSERT INTO OBRAS (AREA, EMPRESA, NUMERO, CONTRATA, AÑO, ETAPA, OBRA, BARRIO, DESCRIPCION) VALUES 
(1, 1, 80, 1, 2023, 0, 0, 1, 'Borde Costero-Contencion Macizo'),
(2, 2, 12, 2, 2024, 1, 1, 2, 'Mantenimiento integral'),
(2, 3, 68, 3, 2023, 1, 1, 14, 'Recuperación de fachadas y trabajos complementarios'),
(2, 4, 9, 4, 2023, 1, 1, 7, 'Piedrabuena - Recup. y renov. inst. de gas');

INSERT INTO AUTORIZANTES (OBRA, DETALLE, CONCEPTO, ESTADO, EXPEDIENTE, MONTO_AUTORIZADO, AUTORIZACION_GG)
VALUES (1, 'Obra Basica', 'Basica', 1, '44385963/23', 898753854.00, 1);

INSERT INTO AUTORIZANTES (OBRA, DETALLE, CONCEPTO, ESTADO, EXPEDIENTE, MONTO_AUTORIZADO, AUTORIZACION_GG)
VALUES (3, 'Obra Basica', 'Basica', 1, '33049761/23', 53809013.20, 1);

INSERT INTO AUTORIZANTES (OBRA, DETALLE, CONCEPTO, ESTADO, EXPEDIENTE, MONTO_AUTORIZADO, AUTORIZACION_GG)
VALUES (3, 'Adenda 1', 'Adenda', 3, NULL, NULL, 1);

INSERT INTO AUTORIZANTES (OBRA, DETALLE, CONCEPTO, ESTADO, EXPEDIENTE, MONTO_AUTORIZADO, AUTORIZACION_GG)
VALUES (4, 'Obra Basica', 'Basica', 1, '05567301/23', 95251093.00, 1);

INSERT INTO AUTORIZANTES (OBRA, DETALLE, CONCEPTO, ESTADO, EXPEDIENTE, MONTO_AUTORIZADO, AUTORIZACION_GG)
VALUES (4, 'Adicional 01', 'Adicional', 1, '14243383/24', 3006811.19, 1);

INSERT INTO AUTORIZANTES (OBRA, DETALLE, CONCEPTO, ESTADO, EXPEDIENTE, MONTO_AUTORIZADO, AUTORIZACION_GG)
VALUES (4, 'Obra Basica REDET 01', 'Basica', 1, '05567301/23', 3006811.19, 1);

INSERT INTO AUTORIZANTES (OBRA, DETALLE, CONCEPTO, ESTADO, EXPEDIENTE, MONTO_AUTORIZADO, AUTORIZACION_GG)
VALUES (4, 'Adicional REDET 01', 'Adicional', 1, '14243383/24', 3006811.19, 1);


INSERT INTO REDETERMINACIONES (ID_BASE, CODIGO_AUTORIZANTE, EXPEDIENTE, SALTO, NRO, TIPO, ETAPA, OBSERVACIONES) VALUES 
(4, '4-00', '15889674/24', '2023-10-01', 1, 'Provisoria', 1, 'ASDASDASDASDASD'),
(4, '4-1', '22255333/24', '2023-10-01', 1, 'Provisoria', 2, 'ASDASDASDASDASDDDDD');
INSERT INTO DISPOSICIONES (EXPEDIENTE, FECHA, DISPO, INFO_NOTIFICACION) VALUES 
('15889674/24', '2024-06-12', 'DI-2024-420-GCABA-IVC', 'IF-2024-23099982-GCABA-IVC');
INSERT INTO ACTAS_ACUERDO (EXPEDIENTE, FECHA, ACTA_ACUERDO, RTA_DICTAMEN) VALUES 
('15889674/24', '2024-04-05', 'IF-2024-14856183-GCABA-IVC', 'IF-2024-14862711-GCABA-IVC');

INSERT INTO CERTIFICADOS (CODIGO_AUTORIZANTE, EXPEDIENTE_PAGO, TIPO_PAGO, MONTO_TOTAL, MES_APROBACION) VALUES 
('1-1', '35398238/24', 1, 89875385.45, '2024-09-01'),
('1-1', '43018058/24', 2, 103904672.40, '2024-10-01'),
('1-1', '45381115/24', 2, 138884433.13, '2024-11-01'),
('1-1', NULL, 2, 136134246.34, '2024-12-01'),
('1-1', NULL, 2, 114860742.60, '2025-01-01'),
('1-1', NULL, 2, 116640275.24, '2025-02-01'),
('1-1', NULL, 2, 101352472.17, '2025-03-01'),
('1-1', NULL, 2, 97065416.28, '2025-04-01'),
('4-1', '37048873/23', 1, 14287664.00, '2023-10-01'),
('4-1', '01487314/24', 2, 8774302.66, '2023-12-01'),
('4-1', '05996239/24', 2, 4531030.95, '2024-01-01'),
('4-1', '10435888/24', 2, 10474191.66, '2024-02-01'),
('4-1', '13279211/24', 2, 9815034.88, '2024-03-01'),
('4-1', '16896366/24', 2, 12799777.99, '2024-04-01'),
('4-1', '22660767/24', 2, 9088213.12, '2024-05-01'),
('4-1', NULL, 2, 1500000.00, '2024-11-01'),
('4-1', '25839020/24', 2, 15391340.41, '2024-06-01'),
('4-1', '29355102/24', 2, 3683892.59, '2024-07-01'),
('4-1', '34121717/24', 2, 3741706.56, '2024-08-01'),
('4-1', '38571234/24', 2, 1500000.00, '2024-09-01'),
('4-1', '42977092/24', 2, 1740868.76, '2024-10-01'),
('4-1', NULL, 2, 1500000.00, '2024-12-01'),
('4-2', '29348658/24', 2, 7899813.59, '2024-07-01'),
('4-2', '34538730/24', 2, 7899813.58, '2024-08-01'),
('4-2', '38853348/24', 2, 85945.56, '2024-09-01'),
('4-2', '42788007/24', 2, 244153.44, '2024-10-01'),
('4-2', NULL, 2, 287662.00, '2024-12-01');
INSERT INTO LEGITIMOS_ABONOS (CODIGO_AUTORIZANTE, OBRA, EXPEDIENTE, INICIO_EJECUCION, FIN_EJECUCION, CERTIFICADO, MES_APROBACION) VALUES
('PL-LA-MANT', 2, '04782891/24', '2023-11-01', '2023-11-30', 15215215.04, '2023-11-01'),
('PL-LA-MANT', 2, '04811207/24', '2023-12-01', '2023-12-31', 15628208.50, '2023-12-01'),
('PL-LA-MANT', 2, '13537241/24', '2024-01-01', '2024-01-31', 34000000.00, '2024-01-01'),
('PL-LA-MANT', 2, '13541632/24', '2024-02-01', '2024-02-29', 37400000.00, '2024-02-01'),
('PL-LA-MANT', 2, '20509827/24', '2024-03-01', '2024-03-31', 37500000.03, '2024-03-01'),
('PL-LA-MANT', 2, '20505780/24', '2024-04-01', '2024-04-30', 41250000.00, '2024-04-01'),
('PL-LA-MANT', 2, '26767862/24', '2024-05-01', '2024-05-31', 45375000.01, '2024-05-01'),
('PL-LA-MANT', 2, '27429366/24', '2024-06-01', '2024-06-30', 49912500.05, '2024-06-01'),
('PL-LA-MANT', 2, '32250359/24', '2024-07-01', '2024-07-31', 52000000.01, '2024-07-01'),
('PL-LA-MANT', 2, '35621083/24', '2024-08-01', '2024-08-30', 54600000.01, '2024-08-01'),
('PL-LA-MANT', 2, '39437717/24', '2024-09-01', '2024-09-30', 57330000.00, '2024-09-01'),
('PL-LA-MANT', 2, '43039990/24', '2024-10-01', '2024-10-31', 60196500.01, '2024-10-01'),
('PL-LA-MANT', 2, NULL, '2024-11-01', '2024-11-30', 63206325.01, '2024-11-01'),
('PL-LA-MANT', 2, NULL, '2024-12-01', '2024-12-31', 66366641.26, '2024-12-01');
INSERT INTO LINEA_DE_GESTION (NOMBRE) VALUES 
('Rodrigo Bueno'),('Fraga'),('Resto inversiones IVC');
INSERT INTO BD_PROYECTOS (ID_BASE, SUBPROYECTO, PROYECTO, LINEA_DE_GESTION, AUTORIZADO_INICIAL) VALUES
(1, 'Borde Costero-Contencion Macizo', 'Rodrigo Bueno (Infraestructura) (N)', 1, 347612380.00),
(2, 'Mantenimiento integral', 'Atención de emergencias y mantenimiento en barrios populares y conjuntos urbanos', 2, 268022699.00),
(3, 'Recuperación de fachadas y trabajos complementarios', 'Barrio 15 (Mejoramientos)', 3, 100000000.00),
(4, 'Piedrabuena - Recup. y renov. inst. de gas', 'Conjunto Piedrabuena (C)', 3, 153335159.00);
--
INSERT INTO MOVIMIENTOS_GESTION (ID_BASE , MOVIMIENTO, FECHA) VALUES 
(1,100000000.00,'2024-12-01'),
(3,-100000000.00,'2024-12-01')

SELECT * FROM EMPRESAS
SELECT * FROM BARRIOS
SELECT NOMBRE FROM AREAS
SELECT * FROM CONTRATA
SELECT * FROM OBRAS
SELECT * FROM BD_PROYECTOS
-- SELECT OBRAS
SELECT O.ID,A.NOMBRE AS AREA,E.NOMBRE AS EMPRESA,NUMERO,C.NOMBRE AS CONTRATA,AÑO,ETAPA,OBRA,B.NOMBRE AS BARRIO,DESCRIPCION FROM OBRAS AS O 
INNER JOIN EMPRESAS AS E ON O.EMPRESA = E.ID 
INNER JOIN AREAS AS A ON O.AREA = A.ID 
INNER JOIN CONTRATA AS C ON O.CONTRATA = C.ID
INNER JOIN BARRIOS AS B ON O.BARRIO = B.ID
--
SELECT * FROM AUTORIZANTES
SELECT CONCAT(C.NOMBRE,' ',O.NUMERO,'/',O.AÑO) AS CONTRATA, O.DESCRIPCION AS OBRA, CODIGO_AUTORIZANTE, DETALLE, CONCEPTO,E.NOMBRE AS ESTADO, EXPEDIENTE, MONTO_AUTORIZADO, AUTORIZACION_GG,AR.NOMBRE as AREA FROM AUTORIZANTES AS A
INNER JOIN OBRAS AS O ON A.OBRA = O.ID
INNER JOIN ESTADOS_AUTORIZANTES AS E ON A.ESTADO = E.ID
INNER JOIN CONTRATA AS C ON O.CONTRATA = C.ID
INNER JOIN BD_PROYECTOS AS B ON O.ID = B.ID_BASE
inner join AREAS as AR on o.AREA = AR.ID
--
select * from CERTIFICADOS
SELECT CONCAT(CO.NOMBRE,' ',O.NUMERO,'/',O.AÑO) AS CONTRATA, O.DESCRIPCION, C.CODIGO_AUTORIZANTE, EXPEDIENTE_PAGO, T.NOMBRE as Tipo_Pago, MONTO_TOTAL, MES_APROBACION, A.MONTO_AUTORIZADO, FORMAT((MONTO_TOTAL / A.MONTO_AUTORIZADO) * 100, 'N2') AS PORCENTAJE, B.AUTORIZADO_NUEVO FROM CERTIFICADOS AS C
INNER JOIN TIPO_PAGO AS T ON C.TIPO_PAGO = T.ID
INNER JOIN AUTORIZANTES AS A ON C.CODIGO_AUTORIZANTE = A.CODIGO_AUTORIZANTE
INNER JOIN OBRAS AS O ON A.OBRA = O.ID
INNER JOIN CONTRATA AS CO ON O.CONTRATA = CO.ID
left JOIN BD_PROYECTOS AS B ON O.ID = B.ID_BASE

 
 INSERT INTO USUARIOS (NOMBRE, CORREO, CONTRASENIA, TIPO,ESTADO,AREA) OUTPUT INSERTED.NOMBRE
VALUES ('admin', '123@gmail.com', '123',1,1,2);
SELECT * FROM ESTADOS_AUTORIZANTES


SELECT 
    CONCAT(C.NOMBRE, ' ', O.NUMERO, '/', O.AÑO) AS CONTRATA, 
    O.DESCRIPCION AS OBRA, 
    A.CODIGO_AUTORIZANTE, 
    A.DETALLE, 
    A.CONCEPTO, 
    E.NOMBRE AS ESTADO, 
    E.ID AS ESTADO_ID, 
    A.EXPEDIENTE, 
    A.MONTO_AUTORIZADO,
	A.MES,
    A.AUTORIZACION_GG, 
    AR.NOMBRE AS AREA, 
    AR.ID AS AREA_ID, 
    C.ID AS CONTRATA_ID
FROM 
    AUTORIZANTES AS A
INNER JOIN 
    OBRAS AS O ON A.OBRA = O.ID
INNER JOIN 
    ESTADOS_AUTORIZANTES AS E ON A.ESTADO = E.ID
INNER JOIN 
    CONTRATA AS C ON O.CONTRATA = C.ID
LEFT JOIN 
    BD_PROYECTOS AS B ON O.ID = B.ID_BASE
INNER JOIN 
    AREAS AS AR ON O.AREA = AR.ID