//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
//
//     Los cambios en este archivo podrian causar un comportamiento incorrecto y se perderan si
//     se vuelve a generar el codigo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebForms
{
    public partial class Inicio
    {
        /// <summary>
        /// pnlEmpty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmpty;

        /// <summary>
        /// rptPages control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPages;
    }
}
